<span style="font-size:30px;">các hoạt động thiết lập Numpy</span>


<span style="font-size:20px;">unique: tìm các phần tử duy nhất từ 1 mảng</span>


In [1]:
# Chuyển đổi mảng sau với các phần tử lặp lại thành 1 tập hợp
import numpy as np
arr = np.array([1,2,1,1,3,4,5,6,7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


In [2]:
# Tìm giá trị duy nhất của 2 mảng: union1d()
 # Tìm hợp của 2 mảng
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
x = np.union1d(arr1, arr2)
print(x)

[1 2 3 4 5 6 7]


<span style="font-size:20px;">Tìm giao điểm</span>


In [4]:
# Tìm các giá tị chỉ có trong cả 2 mảng: intersect1d()
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
x = np.intersect1d(arr1, arr2, assume_unique=True)
print(x)

[3 4 5]


<span style="font-size:30px;">Tìm kiếm sự khác biệt</span>


In [5]:
# Tìm gía trị có trong tập 1 không có trong tập thứ 2: setdiff1d()
import numpy as np
set1 = np.array([1,2,3,4,5])
set2 = np.array([5,6,7,8,9])
x = np.setdiff1d(set1, set2, assume_unique=True)
print(x)

[1 2 3 4]


<span style="font-size:20px;">Tìm sự khác biệt đối xứng</span>


In [6]:
# tìm các giá trị không có trong cả 2 tập hợp: setxor1d()
import numpy as np
set1 = np.array([1,2,3,4])
set2 = np.array([3,5,6,4])
x = np.setxor1d(arr1, arr2, assume_unique=True)
print(x)

[1 2 6 7]
