<span style="font-size:30px;">Số học đơn giản</span>


<span style="font-size:20px;">phép cộng: add()</span>


In [1]:
# Thêm các giá trị trong arr1 vào các giá trị trong arr2
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([8,9,10,11,12,13,14])

newarr = np.add(arr1, arr2)
print(newarr)

[ 9 11 13 15 17 19 21]


<span style="font-size:20px;">Phép trừ: subtract()</span>


In [5]:
# Dùng hàm: subtract()
 # trừ các giá trị trong arr2 khỏi các gía trị trong arr1
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([8,9,10,11,12,13,14])

newarr = np.subtract(arr1, arr2)
print(newarr)

[-7 -7 -7 -7 -7 -7 -7]


<span style="font-size:20px;">Phép nhân: multiply</span>


In [6]:
# Nhân các gía trị trong arr1 với các giá trị trong arr2
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([8,9,10,11,12,13,14])

newarr = np.multiply(arr1,arr2)
print(newarr)

[ 8 18 30 44 60 78 98]


<span style="font-size:20px;">Phép chia: divide()</span>


In [9]:
# Chía các giá trị trong arr2 với arr1
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([8,9,10,11,12,13,14])

newarr = np.divide(arr2, arr1)
print(newarr)


[8.         4.5        3.33333333 2.75       2.4        2.16666667
 2.        ]


<span style="font-size:20px;">Hàm mũ: power()</span>


In [11]:
# Nâng các giá trị trong arr1 lên lũy thừa các giá trị trong arr2
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([8,3,10,11,12,13,14])

newarr = np.power(arr1, arr2)
print(newarr)

[           1            8        59049      4194304    244140625
  13060694016 678223072849]


<span style="font-size:30px;">Phần còn lại:  mod(), remainder()</span>


In [16]:
# Trả về số dư: mod()
# lấy arr2 chia arr1 và lấy số dư
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([8,9,10,11,12,13,14])

newarr = np.mod(arr2,arr1)
print(newarr)

[0 1 1 3 2 1 0]


In [17]:
# Trả về số dư: remainder()
# lấy arr2 chia arr1 và lấy số dư
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([8,9,10,11,12,13,14])

newarr = np.remainder(arr2,arr1)
print(newarr)

[0 1 1 3 2 1 0]


<span style="font-size:20px;">Thương và mod(): divmod()</span>


In [18]:
# trả về 2 mảng, mảng thứ 1 là thương và mảng thứ 2 chứa mod(dư)
# lấy arr2 chia arr1 và lấy số thương và dư
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([8,9,10,11,12,13,14])

newarr = np.divmod(arr2,arr1)
print(newarr)

(array([8, 4, 3, 2, 2, 2, 2]), array([0, 1, 1, 3, 2, 1, 0]))


<span style="font-size:20px;">Gía trị tuyệt đối: absolute()</span>


In [20]:
# trả về giá trị tuyệt đối
import numpy as np
arr = np.array([-1,-2, 1, 3, 4 , -4])

newarr = np.absolute(arr)
print(newarr)

[1 2 1 3 4 4]
