<span style="font-size:30px;">Hàm lượng giác: sin</span>


In [2]:
# Tìm gía trị sin của pi/2
import numpy as np
x = np.sin(np.pi/2)
print("sin(pi/2) =",x)

sin(pi/2) = 1.0


In [4]:
# Tìm giá trị sin cho tất cả các giá trị trong arr
import numpy as np
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)
               

[1.         0.8660254  0.70710678 0.58778525]


<span style="font-size:30px;">Chuyển đổi độ sang radian</span>


In [6]:
# Chuyển đổi tất cả các gía trị trong mảng arr sau sang radian
import numpy as np
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


<span style="font-size:30px;">Chuyển đổi radian sang độ</span>


In [8]:
# chuyển tất cả các giá trị trong mảng sau sang độ
import numpy as np
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)


[ 90. 180. 270. 360.]


<span style="font-size:30px;">Tìm góc</span>


In [9]:
# Tìm góc 1.0
import numpy as np
x = np.arcsin(1.0)
print(x)

1.5707963267948966


<span style="font-size:30px;">Góc của mỗi giá trị trong mảng</span>


In [11]:
# Tìm góc cho tất cả các giá trị sin trong mảng
import numpy as np
arr = np.array([1, -1, 0 , 1])
x = np.arcsin(arr)
print(x)

[ 1.57079633 -1.57079633  0.          1.57079633]


<span style="font-size:30px;">Cạnh huyền</span>


In [15]:
# Tìm cạnh huyền của 4 đáy và 3 góc vuông
import numpy as np
base = 3
perp = 4

x = np.hypot(base, perp)
print(x)

5.0
